### ISSUE TITLE
I have no idea what it is, but it looks like an EXILED error.

### ISSUE THREAD

**Issue by Tamago4a** [galaxy119/EXILED#198] opened 2020-08-05 14:01 UTC
![ивенты](https://user-images.githubusercontent.com/47304666/89421527-d6349000-d73c-11ea-8e7b-a11db2491821.png)
List of plugins that I use.
![список плагинов](https://user-images.githubusercontent.com/47304666/89421893-480cd980-d73d-11ea-9367-bd2ed14f7b1b.png)

**Comment by galaxy119** [comment] 2020-08-05 16:04
This is an event error caused by a base-game error, but base-game errors are hidden from the console and logs, so you only see the exiled one. You can generally ignore this error, and it will be addressed in an upcoming update.

**Comment by iRebbok** [comment] 2020-08-07 17:19
Always provide the exception log in text format. Also provide a piece of the log and tell when (after or before the round, etc) it happened.

**Closed** 2020-08-08 00:52 UTC
Labels: bug
